apiVersion: v1
kind: ConfigMap
metadata:
  name: yaksh-config
data:
  SECRET_KEY: dUmMy_s3cR3t_k3y
  DEBUG: "TRUE"
  ALLOWED_URLS: "*"
  DB_ENGINE: "mysql"
  DB_NAME: "yaksh"
  DB_USER: "root"
  DB_PASSWORD: "root"
  DB_HOST: "10.110.179.195"
  DB_PORT: "3306"
  N_CODE_SERVERS: "5"
  SERVER_POOL_PORT: "55555"
  SERVER_HOST_NAME: "10.99.127.108"
    
