apiVersion: v1
kind: Service
metadata:
  name: yaksh-code
spec:
  type: ClusterIP
  clusterIP: 10.99.127.108
  ports:
  - name: yaksh-code
    port: 55555
    protocol: TCP
    targetPort: 55555
  selector:
    app: codeserver
